on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
name: Test project
jobs:
  wait_for_vercel:
    name: Wait for Vercel preview
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    steps:
      - name: Wait for Vercel preview deployment to be ready
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 600
          environment: production
  pa11y:
    name: Pa11y tests
    needs: wait_for_vercel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install -g pa11y-ci --unsafe-perm=true
      - run: pa11y-ci ${{ needs.wait_for_vercel.outputs.preview_url }}
